zipkin:
  url:  http://sr-zipkin:9411/
web:
  upload-path:  D:/file/uj/
spring:
  zipkin:
    base-url: ${zipkin.url}
    enabled: true
  sleuth:
    sampler:
      percentage: 1
  rabbitmq:
    host: ENC(+YJKD0Er8jXxXpb2DVnp097KOVmjUAQ8)
    port: 5672
    username: ENC(SIfHH2M5id/U0ZI03x+Nbg==)
    password: ENC(SIfHH2M5id/U0ZI03x+Nbg==)
# 开启发送确认
    publisher-confirms: true
# 开启发送失败退回
    publisher-returns: true
# 开启ACK
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual
  redis:
    host: ENC(ttbY+nvTWlPDb05Vsi6wqlliA6FwSJ8U)
    #host: 192.168.0.113
    port: 6379
    timeout: 0
    pool:
      max-wait: -1
      max-active: 5
      max-idle: 50
      min-idle: 10
  http:
    multipart:
      maxFileSize: 50Mb
      maxRequestSize: 100Mb
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization: 
      write-dates-as-timestamps: false
logging:
  level: 
    root: info
    com:
      cj: debug
mybatis:
  type-aliases-package: com.cj.common.entity
  mapper-locations: classpath:com/cj/common/mapper/*.xml
tx-lcn:
  client:
    manager-address: ENC(vdESOQXZYndFhdFY850ckoFraCHljumdLNGTr1Z+hkM=)
    tm-rpc-timeout: 2000
ribbon:
  ReadTimeout: 120000
  ConnectTimeout: 30000
  SocketTimeout: 60000
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 600000
