zipkin:
  url:  http://pr.appshowings.com:9411/
web:
  upload-path:  D:/file/uj/
spring:
  zipkin:
    base-url: ${zipkin.url}
    enabled: true
  sleuth:
    sampler:
      percentage: 1
  rabbitmq:
    host: ENC(+YJKD0Er8jXxXpb2DVnp097KOVmjUAQ8)
    port: 5672
    username: ENC(SIfHH2M5id/U0ZI03x+Nbg==)
    password: ENC(SIfHH2M5id/U0ZI03x+Nbg==)
# 开启发送确认
    publisher-confirms: true
# 开启发送失败退回
    publisher-returns: true
# 开启ACK
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual
  redis:
    host: ENC(ttbY+nvTWlPDb05Vsi6wqlliA6FwSJ8U)
    port: 6379
    #客户端超时时间单位是毫秒 默认是2000
    timeout: 10000
    pool:
      #连接池的最大数据库连接数。
      max-active: 10000
      #最大建立连接等待时间,超过将报异常
      max-wait: -1
      #最大空闲数
      max-idle: 300
      min-idle: 50

  http:
    multipart:
      maxFileSize: 50Mb
      maxRequestSize: 100Mb
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization: 
      write-dates-as-timestamps: false
logging:
  level: 
    root: info
    com:
      cj: debug
mybatis:
  type-aliases-package: com.cj.common.entity
  mapper-locations: classpath:com/cj/common/mapper/*.xml
tx-lcn:
  client:
    manager-address: ENC(vdESOQXZYndFhdFY850ckoFraCHljumdLNGTr1Z+hkM=)
    tm-rpc-timeout: 2000
