server:
  tomcat:
    accept-count: 50
    max-threads: 200
    max-connections: 6000
web:
  upload-path:  D:/file/uj/
spring:
  zipkin:
    base-url: http://59.110.164.54:9411
    #本项目服务名
    service:
      name: ${spring.application.name}
    locator:
      discovery:
        enabled: true
    sender:
      type: web
  sleuth:
   #监控开关
    enabled: true
    sampler:
      percentage: 1.0
  rabbitmq:
    host: 139.224.195.76
    port: 5672
    username: ENC(SIfHH2M5id/U0ZI03x+Nbg==)
    password: ENC(SIfHH2M5id/U0ZI03x+Nbg==)
# 开启发送确认
    publisher-confirms: true
# 开启发送失败退回
    publisher-returns: true
# 开启ACK
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual
  redis:
    host: 139.224.195.76
    port: 16379
    timeout: 1
    pool:
      max-wait: -1
      max-active: 5
      max-idle: 50
      min-idle: 10
  http:
    multipart:
      maxFileSize: 50Mb
      maxRequestSize: 100Mb
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization: 
      write-dates-as-timestamps: false
logging:
  level: 
    root: info
    com:
      cj: debug
mybatis:
  type-aliases-package: com.cj.common.entity
  mapper-locations: classpath:com/cj/common/mapper/*.xml
tx-lcn:
  client:
    manager-address: 192.168.1.185:8070
    tm-rpc-timeout: 2000

