spring:
  datasource:
    url: jdbc:mysql://118.123.16.211:3306/ujie?characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true
    username: ENC(9aNi3IHj2H6kZr0ODNHtyA==)
#    password: ENC(9aNi3IHj2H6kZr0ODNHtyA==)
    password: ENC(TkOCIol7cpFd41MfpYYQBK+giiV3zOn3)
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: classpath:com/cj/suser/mapper/*.xml

